version: '3.9'

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    expose:
      - "8000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: simple-frontend
    expose:
      - "80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
