version: '3.9'

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    expose:
      - "8000"
    environment:
      - DB_PORT=5432
      - DB_NAME=avyay
      - DB_USER=avyay_user
      - DB_PASS=avyay123
      - DB_HOST=host.docker.internal
      - JWT_SECRET=avyaysecret
      - REDIS_HOST=reflectredis.redis.cache.windows.ne
      - REDIS_PORT=6380
      - RATE_LIMIT_MODE=fixed
      - AZURE_SAS_TOKEN=sp=rwdl&st=2025-05-10T21:26:06Z&se=2025-05-11T05:26:06Z&sv=2024-11-04&sr=c&sig=%2Fh5yI6WDf3bXFu45qesoUV4voHFK1mJTiUJxONScgTY%3D
      - AZURE_STORAGE_CONNECTION_STRING=https://reflectstorage.blob.core.windows.net/uploads?sp=rwdl&st=2025-05-10T21:26:06Z&se=2025-05-11T05:26:06Z&sv=2024-11-04&sr=c&sig=%2Fh5yI6WDf3bXFu45qesoUV4voHFK1mJTiUJxONScgTY%3D
      - AZURE_STORAGE_CONTAINER_NAME=uploads 
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: simple-frontend
    expose:
      - "80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
