version: '3.9'

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    expose:
      - "8000"
    environment:
      - DB_PORT=5432
      - DB_NAME=avyay
      - DB_USER=avyay_user
      - DB_PASS=avyay123
      - DB_HOST=host.docker.internal
      - JWT_SECRET=avyaysecret
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - RATE_LIMIT_MODE=fixed
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: simple-frontend
    expose:
      - "80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
