apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: reflectns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: reflectacr.azurecr.io/avyay-backend:latest1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: reflectdb.postgres.database.azure.com
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: reflectmain
            - name: DB_USER
              value: reflect
            - name: DB_PASS
              value: dyhcoC-0xodme-byfmum
            - name: REDIS_HOST
              value: reflectred.redis.cache.windows.net
            - name: REDIS_PASS
              value: HinLSU2AFpvbQtSeFf2FLq1i7sJCc2UbzAzCaACs9B4=
            - name: REDIS_PORT
              value: "6380"
            - name: JWT_SECRET
              value: avyaysecret
            - name: RATE_LIMIT_MODE
              value: fixed
            - name: AZURE_SAS_TOKEN
              value: sp=rwdl&st=2025-05-10T21:26:06Z&se=2025-05-11T05:26:06Z&sv=2024-11-04&sr=c&sig=%2Fh5yI6WDf3bXFu45qesoUV4voHFK1mJTiUJxONScgTY%3D
            - name: AZURE_STORAGE_CONNECTION_STRING
              value: DefaultEndpointsProtocol=https;AccountName=reflectstorage;AccountKey=h5PaAwcLOsY0in3OxS4XQwgBLOEsJANeMlLc0/JAERpij/IroYD/E3hkITIG81gHaPNHERR55YES+AStj7xtxw==;EndpointSuffix=core.windows.net
            - name: AZURE_STORAGE_CONTAINER_NAME
              value: uploads
            - name: ENV
              value: production

