apiVersion: batch/v1
kind: Job
metadata:
  name: backend-test
  namespace: reflectns
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 600  # Auto-delete job 10 mins after finish
  template:
    metadata:
      labels:
        app: backend-test
    spec:
      containers:
        - name: backend-test
          image: IMAGE_PLACEHOLDER
          envFrom:
            - secretRef:
                name: reflect-secrets
          command: ["/bin/sh", "-c"]
          args: ["/bin/sh", "-c", "cd /app && PYTHONPATH=. pytest -v --cache-clear --disable-warnings tests/ && curl --fail http://localhost:8000/test-version"]
      restartPolicy: Never
