apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: reflectns
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: reflectacr.azurecr.io/avyay-backend:latest3
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          #env:
          #  - name: DB_HOST
          #    value: reflectdb.postgres.database.azure.com
          #  - name: DB_PORT
          #    value: "5432"
          #  - name: DB_NAME
          #    value: reflectmain
          #  - name: DB_USER
          #    value: reflect
          #  - name: DB_PASS
          #    value: dyhcoC-0xodme-byfmum
          #  - name: REDIS_HOST
          #    value: reflectred.redis.cache.windows.net
          #  - name: REDIS_PASS
          #    value: HinLSU2AFpvbQtSeFf2FLq1i7sJCc2UbzAzCaACs9B4=
          #  - name: REDIS_PORT
          #    value: "6380"
          #  - name: JWT_SECRET
          #    value: avyaysecret
          #  - name: RATE_LIMIT_MODE
          #    value: fixed
          #  - name: AZURE_SAS_TOKEN
          #    value: sp=rwdl&st=2025-05-10T21:26:06Z&se=2025-05-11T05:26:06Z&sv=2024-11-04&sr=c&sig=%2Fh5yI6WDf3bXFu45qesoUV4voHFK1mJTiUJxONScgTY%3D
          #  - name: AZURE_STORAGE_CONNECTION_STRING
          #    value: DefaultEndpointsProtocol=https;AccountName=reflectstorage;AccountKey=h5PaAwcLOsY0in3OxS4XQwgBLOEsJANeMlLc0/JAERpij/IroYD/E3hkITIG81gHaPNHERR55YES+AStj7xtxw==;EndpointSuffix=core.windows.net
          #  - name: AZURE_STORAGE_CONTAINER_NAME
          #    value: uploads
          #  - name: ENV
          #    value: production
          
          env:
            - name: AZURE_SAS_TOKEN
              value: sv=2024-11-04&ss=bf&srt=co&sp=rwdlactfx&se=2025-05-31T14:25:33Z&st=2025-05-11T06:25:33Z&spr=https,http&sig=mcjGtWkXCcOKblFazu0lxYjAYmGXXX9JfWZHE85WPP8%3D
            - name: AZURE_STORAGE_CONNECTION_STRING
              value: DefaultEndpointsProtocol=https;AccountName=reflectstorage;AccountKey=h5PaAwcLOsY0in3OxS4XQwgBLOEsJANeMlLc0/JAERpij/IroYD/E3hkITIG81gHaPNHERR55YES+AStj7xtxw==;EndpointSuffix=core.windows.net
            - name: AZURE_STORAGE_ACCOUNT_KEY
              value: h5PaAwcLOsY0in3OxS4XQwgBLOEsJANeMlLc0/JAERpij/IroYD/E3hkITIG81gHaPNHERR55YES+AStj7xtxw==
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: reflect-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: reflect-secrets
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: reflect-secrets
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: reflect-secrets
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: reflect-secrets
                  key: DB_PASS
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: reflect-secrets
                  key: REDIS_HOST
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: reflect-secrets
                  key: REDIS_PASS
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: reflect-secrets
                  key: REDIS_PORT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: reflect-secrets
                  key: JWT_SECRET
            - name: RATE_LIMIT_MODE
              value: fixed
            #- name: AZURE_SAS_TOKEN
            #  valueFrom:
            #    secretKeyRef:
            #      name: reflect-secrets
            #      key: AZURE_SAS_TOKEN
            #- name: AZURE_STORAGE_CONNECTION_STRING
            #  valueFrom:
            #    secretKeyRef:
            #      name: reflect-secrets
            #      key: AZURE_STORAGE_CONNECTION_STRING
            - name: AZURE_STORAGE_CONTAINER_NAME
              valueFrom:
                secretKeyRef:
                  name: reflect-secrets
                  key: AZURE_STORAGE_CONTAINER_NAME
            - name: ENV
              value: production
