apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: reflectns
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: reflectacr.azurecr.io/avyay-backend:latest3
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: reflect-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: reflect-secrets
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: reflect-secrets
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: reflect-secrets
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: reflect-secrets
                  key: DB_PASS
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: reflect-secrets
                  key: REDIS_HOST
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: reflect-secrets
                  key: REDIS_PASS
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: reflect-secrets
                  key: REDIS_PORT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: reflect-secrets
                  key: JWT_SECRET
            - name: RATE_LIMIT_MODE
              value: fixed
            - name: AZURE_SAS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: reflect-secrets
                  key: AZURE_SAS_TOKEN
            - name: AZURE_STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: reflect-secrets
                  key: AZURE_STORAGE_CONNECTION_STRING
            - name: AZURE_STORAGE_CONTAINER_NAME
              valueFrom:
                secretKeyRef:
                  name: reflect-secrets
                  key: AZURE_STORAGE_CONTAINER_NAME
            - name: AZURE_STORAGE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: reflect-secrets
                  key: AZURE_STORAGE_ACCOUNT_KEY
            - name: ENV
              value: production
