apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: reflectns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: reflectacr.azurecr.io/avyay-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: your-azure-postgres-host
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: avyay
            - name: DB_USER
              value: avyay_user
            - name: DB_PASS
              value: avyay123
            - name: REDIS_HOST
              value: your-azure-redis-host
            - name: REDIS_PORT
              value: "6379"
            - name: JWT_SECRET
              value: avyaysecret
            - name: RATE_LIMIT_MODE
              value: fixed
