name: CI - Build Check

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Docker Build Check - Backend
      run: docker build -t reflects-backend ./backend

    - name: Docker Build Check - Frontend
      run: docker build -t reflects-frontend ./frontend
