name: CI & Push to ACR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      ACR_NAME: reflectacr
      ACR_LOGIN_SERVER: reflectacr.azurecr.io

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master

      - name: Scan Backend Dockerfile (config scan)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: ./backend
          format: table
          exit-code: 1

      - name: Build Backend Image
        run: |
          docker buildx create --use || true
          docker buildx build --platform linux/amd64 -t $ACR_LOGIN_SERVER/avyay-backend:latest ./backend --load

      - name: Scan Backend Image (vulnerability scan)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ACR_LOGIN_SERVER }}/avyay-backend:latest
          format: table
          exit-code: 1
          ignore-unfixed: true

      - name: Push Backend Image
        run: docker push $ACR_LOGIN_SERVER/avyay-backend:latest

      - name: Build Frontend Image
        run: |
          docker buildx build --platform linux/amd64 -t $ACR_LOGIN_SERVER/avyay-frontend:latest ./frontend --load

      - name: Scan Frontend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ACR_LOGIN_SERVER }}/avyay-frontend:latest
          format: table
          exit-code: 1
          ignore-unfixed: true

      - name: Push Frontend Image
        run: docker push $ACR_LOGIN_SERVER/avyay-frontend:latest
